title: Fly Fairly
email: info@flyfairly.co.uk
description:  "If your flight's delayed or cancelled, we can help you claim hundreds in compensation. Start your claim today."
# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  wearethoughtfox

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

include:
  - _pages

sass:
  sass_dir:          _scss
  style:            :compressed

collections:
  rights:
    output: true
    permalink: /:collection/:slug
  howitworks:
    output: true
    permalink: /:collection/:slug
  help:
    output: true
    permalink: /:collection/:slug

include:
  - _pages    

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
